version: "3.3"
services:
# This is a template service used to build the Image and as a starting point for making multiple instances on a single host
  template:
    build: .
    image: minecraft:template
    container_name: template
    ports:
      - 25565:25565
    volumes:
      - "/Minecraft_Server_Docker/Template:/Minecraft"